### ISSUE TITLE
Support for Secrets Managers

### ISSUE THREAD

**Issue by astorm** [elastic/apm-aws-lambda#105]
At present, APM Server credentials are stored in env. variables.  In addition to this standard method for supplying credentials we should investigate Secrets Managers ([such as AWS Secrets Manager](https://aws.amazon.com/secrets-manager/) and determine how feasible it would be to allows the APM Server credentials to be stored and fetched via a secrets manager API

Next steps

- [ ] General Investigation of AWS Secrets Manager (look for blockers, challenges, etc.)
- [ ] Other Secrets Managers?
- [ ] Write Extension code to fetch secrets and populated needed credentials
- [ ] Document use of the secrets manager for end users

**Comment by trentm** [comment]
https://aws.amazon.com/blogs/compute/creating-aws-lambda-environmental-variables-from-aws-secrets-manager/ shows example Go code for querying the AWS Secrets Manager, I believe.

**Comment by rpivovar-godaddy** [comment]
Thanks for this issue @astorm. And thanks for sharing that blog post @trentm -- I've been trying to do something similar to what's outlined in that blog post for Node, but unable to get it to work. 

In that blog post, they are adding the environment variables to the environment by sourcing a file, like:

```sh
set -euo pipefail

OWN_FILENAME="$(basename $0)"
tempFile=$(mktemp /tmp/$OWN_FILENAME}.XXXXXXXX)

echo "export ONE="\two\"" >> ${tempFile}
. ${tempFile}
```

This example would set an environment variable `ONE` to value `"two"`.

If I were to run this script and then run a Node script that contains:

```js
console.log(process.env.ONE);
```

It would print `"two"`.

For some reason, this does not work for me with a Lambda wrapper script and a NodeJS lambda...

**Comment by trentm** [comment]
> ```shell
> set -euo pipefail
> 
> OWN_FILENAME="$(basename $0)"
> tempFile=$(mktemp /tmp/$OWN_FILENAME}.XXXXXXXX)
> 
> echo "export ONE="\two\"" >> ${tempFile}
> . ${tempFile}
> ```

@rpivovar-godaddy I noticed a slight typo in your script. The line:

```shell
echo "export ONE="\two\"" >> ${tempFile}
```

should probably be:

```shell
echo "export ONE=\"two\"" >> ${tempFile}
```

I'm not sure if that is the issue you are hitting, however.

**Comment by rpivovar-godaddy** [comment]
Ah thanks, I had mistyped that in the comment, but it is how you have it in the actual script.

**Comment by trentm** [comment]
Are you `exec`ing your Node script from that same shell script?  That sourced `ONE` envvar will only be defined for that shell script's process tree.

The full shell script example for this AWS doc is more illustrative: https://github.com/aws-samples/aws-lambda-environmental-variables-from-aws-secrets-manager/blob/main/src/get-secrets-layer#L81-L102

**Comment by rpivovar-godaddy** [comment]
Aaaah that makes sense. No, I'm not -- I was expecting this `ONE` variable to present in the handler itself. This wrapper script does not directly call the lambda. Is there any way to add environment variables to the handler from the wrapper script, or from any other extension/layer code?

**Comment by rpivovar-godaddy** [comment]
I'm missing a lot of what's in that full shell script -- going to poke around in there and see what happens. I'll follow up.

**Comment by trentm** [comment]
I haven't played with them myself, but I believe you need to follow the instructions at https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html#runtime-wrapper

Basically, you need to configure a given Lambda Function to have the envvar `AWS_LAMBDA_EXEC_WRAPPER` set to the full path of the wrapper script. It is the job of the wrapper script to (a) do whatever init it wants (e.g. getting data from AWS Secrets Manager), then (b) `exec`ing the lambda function handler (the exec args are passed to the wrapper script).  The link above shows a much smaller example.

I think, theoretically, if/when we would add support to the Elastic Lambda *extension* for secrets support, we would support a configuration option (and environment variable) to would say "Please go get the APM Server `apiKey` or `secretToken` from AWS Secrets Manager using this `secretArn` and `roleName`."   The extension is a separate independent process, so doesn't have a way to inject environment variables in the the application process where the APM Agent is running.

**Comment by rpivovar-godaddy** [comment]
I've finally gotten secrets prefetching working in a lambda extension. Thanks again @trentm for the insight.

However, I'm still having issues getting this to work correctly with apm-aws-lambda.

To try and get this working with secrets, I have:
- extension 1: prefetches secrets and sets them as environment variables.
- extension 2: the APM lambda extension.

I am now getting an error saying that some of environment variables which are set from the secrets prefetch extension are not correctly set, and so the APM lambda extension crashes.

It looks like this is happening because Lambda extensions run in parallel. My prefetch extension uses Node.js while the APM lambda extension uses Go, and my extension is fetching a secret, so it seems like the APM lambda extension will always beat the prefetch extension in execution time. (just a guess)

I then tried to take the APM Lambda extension binary (x86_64 v0.0.3), bundled it along with the other extension, and called it from the wrapper script of the prefetch extension. This looks like:

```sh
echo "Prefetching secrets..."
secrets=$(node ${script_full_path}/index.js)

# Create a temp file to hold values to be exported
tempFile=$(mktemp /tmp/${name}.XXXXXXX)
last_cmd=$?
if [[ ${last_cmd} -ne 0 ]]; then
	echo "Failed to create a temp file"
	exit 1
fi

echo "Secrets prefetched."

while IFS=';' read -ra ADDR; do
	for i in "${ADDR[@]}"; do
		echo "export $i" >> ${tempFile}
	done
done <<< "$secrets"

# source env file which contains secrets. This sets all necessary APM env vars on the environment
. ${tempFile}

# attempting to call the apm-lambda-extension go binary
apm_extension=$(${script_full_path}/apm-lambda-extension)

exec "${args[@]}"
```

This likely won't work because this prefetching layer is executing within a nodejs layer runtime, and calling a Go binary inside of here is probably weird.

It looks like this maybe could work if the extensions weren't run in parallel, but not sure how best to do that.

**Comment by rpivovar-godaddy** [comment]
If it helps anyone, here is how I'm prefetching secrets in the node script. This works with the above script and will set environment vars on `process.env` before the main handler runs -- the `apm_extension` line above just needs to be removed above since that was an experiment.

```js
#!/usr/bin/env node
const AWS = require('aws-sdk');

async function main() {
  const secretsManager = new AWS.SecretsManager();
  const { SecretString } = await secretsManager
    .getSecretValue({ SecretId: 'some_secret' })
    .promise();

  const { secret1, secret2 } = JSON.parse(SecretString);

  process.stdout.write(
    `ELASTIC_APM_LAMBDA_APM_SERVER=${secret1};ELASTIC_APM_SECRET_TOKEN=${secret2}`
  );
}

process.on('unhandledRejection', (e) => {
  console.log('unhandled error', e);

  process.exit(1);
});

(async function () {
  await main();
})();
```

**Comment by rpivovar-godaddy** [comment]
@trentm @astorm thanks again for all the help here.
To sum up, it looks like the apm-aws-lambda will work with secrets if there is another extension which prefetches the secrets.

The problem, though, is that it looks like Lambda extensions execute in parallel. If apm-aws-lambda can execute after the prefetching extension, then it seems like it will work.

Maybe apm-aws-lambda could also fetch secrets, but not sure whether that's a good idea?

**Comment by trentm** [comment]
IIUC, your wrapper script (docs: https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html#runtime-wrapper) is the same process as your application, in which the APM agent is running.  So your app and the APM agent will see the `ELASTIC_APM_LAMBDA_APM_SERVER` and  `ELASTIC_APM_SECRET_TOKEN` envvars that have been set. However, the Elastic APM Lambda *extension* is a separate process, with an independent environment that doesn't get those envvars. And it is the *extension* that needs and uses those two settings.

Throwing out some potential options:
1. Have some new mechanism so the APM *agent* can receive the APM server connection details and pass those to the extension that is listening at localhost:8200.
2. Add support to the extension for it to fetch secrets from AWS Secrets Manager itself. So, instead of setting `ELASTIC_APM_SECRET_TOKEN=sekrit` on the Lambda function's configuration, the user would set something like `ELASTIC_APM_SECRET_TOKEN_FROM_KMS=arn:aws:kms:us-east-1:123456789012:key/1234abcd-12ab34cd-56ef-1234567890ab` (I don't know if a KMS ARN would be appropriate here. I don't know KMS and Secrets Manager that well yet).
3. Add some other more generic support to the extension for secrets management, so that it isn't restricted to AWS Secrets Manager, e.g. support for Hashicorp Vault might be a common desire.

**Comment by simitt** [comment]
@AlexanderWert was working on a POC which is planned to become production ready.

**Comment by AlexanderWert** [comment]
@simitt Here's the PR: https://github.com/elastic/apm-aws-lambda/pull/208
