### ISSUE TITLE
High-level code review before GA

### ISSUE THREAD

**Issue by estolfo** [elastic/apm-aws-lambda#124]
Before we GA the aws lambda extension, we should have an experienced Go engineer from another team (preferably the apm server team) review the codebase.

**Comment by simitt** [comment]
@elastic/apm-server team please conduct a high level review. The goal is to agree on a GA ready state of the code. 
I suggest we put some focus points on the review:
* [ ] are errors properly handled
* [ ] any kind of deadlocks or unexpected blocking on channels; are channels closed while still consumed, etc. 
* [ ] handling of incoming data
* [ ] handling of outgoing requests to apm-server
* [ ] general data structs (allocations, references, ..)
* [ ] e2e test coverage
* [ ] unit test coverage

This is not expected to be included as go module in other programs, therefore reviewing public interfaces etc. has less priority. The `cli` is written in `nodejs`, therefore please ignore this part in the `golang` review.

**Comment by estolfo** [comment]
If someone needs an overview of the code structure before doing a review, please let us know.

**Comment by axw** [comment]
I've just started looking in the `logsapi` package, and how it is used, and here are some initial thoughts:

If you're not familiar with it already, I'd suggest having a look through https://github.com/golang/go/wiki/CodeReviewComments. This is followed in many Go projects, to the point that some linters have checks for the rules. You might have a bad time if you want to turn on linting later on.

Some more detailed code docs would be great. As I'm not familiar Lambda internals, or the Logs API, it wasn't clear to me what the HTTP listener was for. Linking to the relevant parts of https://docs.aws.amazon.com/lambda/latest/dg/runtimes-logs-api.html may be helpful to future readers.

Does everything that is exported need to be exported? Having a minimal public interface helps clarify which parts are implementation details, and which parts are relevant to consumers. e.g. should users of this package care about the different protocols? I realise @simitt said "This is not expected to be included as go module in other programs, therefore reviewing public interfaces etc. has less priority.", but I still think it's important for future maintainers.

The Logs API docs state:

> We also recommend setting up the local HTTP listener or the TCP port before subscribing to receive logs.

It appears that this is not being done. In main.go, subscription is happening first, and then a listener is created and finally started: https://github.com/elastic/apm-aws-lambda/blob/b010fd9a5d77d89d8b48a0e679985ee81db96a94/apm-lambda-extension/main.go#L83-L98

Is there any reason this couldn't be abstracted away? Something like:

```go
package logsapi

// Subscribe subscribes to the Lambda Logs API, sending log events to out until ctx is cancelled.
func Subscribe(ctx context.Context, extensionID string, eventTypes []EventType, out chan<- LogEvent) error
```

Internally, `Subscribe` would create an HTTP server (before making the subscribe request) and run it until ctx is cancelled. You might also want to listen on an ephemeral port to avoid any surprises with running multiple subscribers: listen on "sandbox.localdomain:0", and extract the ephemeral port from the `net.Listener.Addr()`.

In main.go, there can be a panic if the "runtimeDoneSignal" channel is closed (e.g. due to "AgentDoneSignal" being signalled), and then a RuntimeDone log event is processed:

https://github.com/elastic/apm-aws-lambda/blob/b010fd9a5d77d89d8b48a0e679985ee81db96a94/apm-lambda-extension/main.go#L170
https://github.com/elastic/apm-aws-lambda/blob/b010fd9a5d77d89d8b48a0e679985ee81db96a94/apm-lambda-extension/main.go#L204

Do you need to explicitly close that channel? It looks like you could just allow it to be garbage collected.

**Comment by axw** [comment]
> Is it ok to not explicitly close a channel and just allow it to be garbage collected? I thought it was good practice to close a channel?

As a general rule, it's OK to not explicitly close it.

**Comment by axw** [comment]
https://github.com/elastic/apm-aws-lambda/blob/86a442cf2afc1df16a30795e5a790a4c67a616e4/apm-lambda-extension/extension/apm_server.go#L39-L59

Should those `log.Printf` be `return err`? If the compression fails, what's in `buf`?

Also, you could avoid some overhead in the case where `ContentEncoding != ""` by doing something like this:

```go
var r io.Reader
if agentData.ContentEncoding != "" {
    r = bytes.NewReader(agentData.Data)
} else {
    encoding = "gzip"
    buf := bufferPool.Get().(*bytes.Buffer)
    defer func() {
        buf.Reset()
        bufferPool.Put(buf)
    }()     
    gw, err := gzip.NewWriterLevel(buf, gzip.BestSpeed)
    if err != nil {
        return err
    }       
    if _, err := gw.Write(agentData.Data); err != nil {
        log.Printf("Failed to compress data: %v", err)
    }
    if err := gw.Close(); err != nil {
        log.Printf("Failed write compressed data to buffer: %v", err)
    }
    r = buf
}
```

**Comment by axw** [comment]
https://github.com/elastic/apm-aws-lambda/blob/86a442cf2afc1df16a30795e5a790a4c67a616e4/apm-lambda-extension/extension/client.go#L108-L111

You should move the defer before the status code check. Always close the response body if Do returns a nil error. Same applies in other methods in this file. A lot of the code is repeated: maybe define a helper function which sends a request to a specified path, and decodes the body into a given `interface{}`?

**Comment by axw** [comment]
https://github.com/elastic/apm-aws-lambda/blob/86a442cf2afc1df16a30795e5a790a4c67a616e4/apm-lambda-extension/extension/route_handlers.go#L41-L50

Check error first, otherwise the `req.Header.Set` calls will panic if there's an error as `req` will be nil. Also, if there's an error, should the handler return a 5xx error status code?

https://github.com/elastic/apm-aws-lambda/blob/86a442cf2afc1df16a30795e5a790a4c67a616e4/apm-lambda-extension/extension/route_handlers.go#L53

The response body isn't being closed.

https://github.com/elastic/apm-aws-lambda/blob/86a442cf2afc1df16a30795e5a790a4c67a616e4/apm-lambda-extension/extension/route_handlers.go#L89-L90

Would it be possible to stream the client's request body to apm-server, rather than reading it into memory?

I'm also wondering if this approach of using channels is necessary, or if the extension could be simplified by using https://pkg.go.dev/net/http/httputil#ReverseProxy? You could set a Director to do compression and tracking of in-flight requests so you can flush.

**Comment by felixbarny** [comment]
>> Is it ok to not explicitly close a channel and just allow it to be garbage collected? I thought it was good practice to close a channel?
>
> As a general rule, it's OK to not explicitly close it.

That sounds similar to the [deprecated](https://stackoverflow.com/questions/56139760/why-is-the-finalize-method-deprecated-in-java-9) Java finalizers that can close resources on GC. If it does work in a similar way, is it really a best practice?

**Comment by axw** [comment]
Go also has  https://pkg.go.dev/runtime#SetFinalizer. Using this tends to be discouraged. I wouldn't say they're the same.

Channels don't actively consume any resources except their memory. Once they're no longer referenced, that memory can be garbage collected. If something were waiting for the channel to be closed, it couldn't be garbage collected. So it depends on the concurrency patterns, but in this case there's nothing using the channel's closure as an event.

**Comment by estolfo** [comment]
- [ ] Turn on linter
- [ ] Some more detailed code docs
- [ ] Setting up the local HTTP listener or the TCP port before subscribing to receive logs
- [ ] Abstract logsapi Subscribe function
- [ ] listen on an ephemeral port to avoid any surprises with running multiple subscribers: listen on "sandbox.localdomain:0", and extract the ephemeral port from the net.Listener.Addr()
  - [ ] just allow `runtimeDoneSignal` channel to be garbage collected in `main.go`
  - [ ] Should those log.Printf be return err? If the compression fails, what's in buf? in `apm_server.go`
  - [ ] avoid some overhead in the case where ContentEncoding != "" in `apm_server.go`
  - [ ] `client.go` You should move the defer before the status code check. Always close the response body if Do returns a nil error. Same applies in other methods in this file. A lot of the code is repeated: maybe define a helper function which sends a request to a specified path, and decodes the body into a given interface{}?
  - [ ] `route_handlers.go` Check error first, otherwise the req.Header.Set calls will panic if there's an error as req will be nil. Also, if there's an error, should the handler return a 5xx error status code?
  - [ ] `route_handlers.go` The response body isn't being closed. Line 53
  - [ ] Would it be possible to stream the client's request body to apm-server, rather than reading it into memory?
  - [ ] I'm also wondering if this approach of using channels is necessary, or if the extension could be simplified by using https://pkg.go.dev/net/http/httputil#ReverseProxy? You could set a Director to do compression and tracking of in-flight requests so you can flush.

**Comment by estolfo** [comment]
@axw Would you like to review the PRs that I'm opening to address your comments? I've opened two so far and there will be a few others.

**Comment by stuartnelson3** [comment]
Spoke this morning with @simitt and @axw, we're all cool with this to go GA

**Comment by simitt** [comment]
Any concerns for closing this issue now and creating new ones when issues are identified in the future?

**Comment by estolfo** [comment]
No concerns, please feel free to close this. Thanks!

**Comment by estolfo** [comment]
Closing, as issues are opened for the remaining two minor points (linter and code docs)
