### ISSUE TITLE
Align ENVs 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-aws-lambda#185]
Review used ENV names and align within the lambda extension, and with variable names used in other apm agents. 

* `ELASTIC_APM_DATA_RECEIVER_TIMEOUT_SECONDS`
* `ELASTIC_APM_DATA_FORWARDER_TIMEOUT_SECONDS`
* `ELASTIC_APM_LAMBDA_APM_SERVER`
* `ELASTIC_APM_LOG_LEVEL`
* `ELASTIC_APM_SEND_STRATEGY`
* `ELASTIC_APM_SECRET_TOKEN`
* `ELASTIC_APM_API_KEY`

We should changed `ELASTIC_APM_LAMBDA_APM_SERVER` to `ELASTIC_APM_SERVER_URL`.

**Comment by AlexanderWert** [comment]
> We should changed ELASTIC_APM_LAMBDA_APM_SERVER to ELASTIC_APM_SERVER_URL

This is intentionally a different ENV name, because the APM agents and extension read from the same set of env vars using `ELASTIC_APM_SERVER_URL` is not possible because it would make the agents send directly to the APM Server instead to the extension.

`ELASTIC_APM_LOG_LEVEL`, `ELASTIC_APM_SECRET_TOKEN` and `ELASTIC_APM_API_KEY` are already aligned with APM agents.

The remaining options are lambda extension specific.

So not sure if anything needs to be done here

**Comment by simitt** [comment]
Thanks for the details Alex. We can close this issue then, as it doesn't seem to be possible to reuse `ELASTIC_APM_SERVER_URL` in an agent backwards compatible way.
